// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import Exchange from './abstract/coinone.js';
import { BadSymbol, BadRequest, ExchangeError, ArgumentsRequired, OrderNotFound, OnMaintenance } from './base/errors.js';
import { Precise } from './base/Precise.js';
import { TICK_SIZE } from './base/functions/number.js';
import { sha512 } from './static_dependencies/noble-hashes/sha512.js';
//  ---------------------------------------------------------------------------
/**
 * @class coinone
 * @augments Exchange
 */
export default class coinone extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'coinone',
            'name': 'CoinOne',
            'countries': ['KR'],
            'rateLimit': 1000,
            'version': 'v2',
            'pro': false,
            'has': {
                'CORS': undefined,
                'spot': true,
                'margin': false,
                'swap': false,
                'future': false,
                'option': false,
                'addMargin': false,
                'cancelOrder': true,
                'closeAllPositions': false,
                'closePosition': false,
                'createMarketOrder': false,
                'createOrder': true,
                'createReduceOnlyOrder': false,
                'createStopLimitOrder': false,
                'createStopMarketOrder': false,
                'createStopOrder': false,
                'fetchBalance': true,
                'fetchBorrowRateHistories': false,
                'fetchBorrowRateHistory': false,
                'fetchClosedOrders': true,
                'fetchCrossBorrowRate': false,
                'fetchCrossBorrowRates': false,
                'fetchCurrencies': true,
                'fetchDepositAddress': false,
                'fetchDepositAddresses': true,
                'fetchDepositAddressesByNetwork': false,
                'fetchFundingHistory': false,
                'fetchFundingRate': false,
                'fetchFundingRateHistory': false,
                'fetchFundingRates': false,
                'fetchIndexOHLCV': false,
                'fetchIsolatedBorrowRate': false,
                'fetchIsolatedBorrowRates': false,
                'fetchLeverage': false,
                'fetchLeverageTiers': false,
                'fetchMarginMode': false,
                'fetchMarkets': true,
                'fetchMarkOHLCV': false,
                'fetchMyTrades': true,
                'fetchOpenInterestHistory': false,
                'fetchOpenOrders': true,
                'fetchOrder': true,
                'fetchOrderBook': true,
                'fetchPosition': false,
                'fetchPositionHistory': false,
                'fetchPositionMode': false,
                'fetchPositions': false,
                'fetchPositionsForSymbol': false,
                'fetchPositionsHistory': false,
                'fetchPositionsRisk': false,
                'fetchPremiumIndexOHLCV': false,
                'fetchTicker': true,
                'fetchTickers': true,
                'fetchTrades': true,
                'reduceMargin': false,
                'setLeverage': false,
                'setMarginMode': false,
                'setPositionMode': false,
                'ws': true,
            },
            'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/38003300-adc12fba-323f-11e8-8525-725f53c4a659.jpg',
                'api': {
                    'rest': 'https://api.coinone.co.kr',
                    'v2Public': 'https://api.coinone.co.kr/public/v2',
                    'v2Private': 'https://api.coinone.co.kr/v2',
                    'v2_1Private': 'https://api.coinone.co.kr/v2.1',
                },
                'www': 'https://coinone.co.kr',
                'doc': 'https://doc.coinone.co.kr',
            },
            'requiredCredentials': {
                'apiKey': true,
                'secret': true,
            },
            'api': {
                'v2Public': {
                    'get': {
                        'range_units': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'markets/{quote_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'markets/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'orderbook/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'trades/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'ticker_new/{quote_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'ticker_new/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'ticker_utc_new/{quote_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'ticker_utc_new/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'currencies': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'currencies/{currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                        'chart/{quote_currency}/{target_currency}': {'cost': 1 / 20, 'api_rate_limit_group': 'public'},
                    },
                },
                'v2Private': {
                    'post': {
                        'account/balance': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'account/deposit_address': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'account/user_info': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'account/virtual_account': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/cancel': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/limit_buy': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/limit_sell': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/limit_orders': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/completed_orders': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/query_order': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'transaction/auth_number': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'transaction/btc': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'transaction/history': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'transaction/krw/history': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                    },
                },
                'v2_1Private': {
                    'post': {
                        'account/balance/all': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'account/balance': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'account/trade_fee': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'account/trade_fee/{quote_currency}/{target_currency}': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'order/active_orders': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/detail': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/complete_orders/all': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/complete_orders': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/cancel/all': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'order/cancel': {'cost': 1 / 40, 'api_rate_limit_group': 'private'},
                        'transaction/krw/history': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'transaction/coin/history': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'transaction/coin/history/detail': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'transaction/coin/withdrawal/limit': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'transaction/coin/withdrawal/address_book': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                        'transaction/coin/withdrawal': {'cost': 1 / 80, 'api_rate_limit_group': 'private'},
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': false,
                    'percentage': true,
                    'taker': 0.0001,
                    'maker': 0,
                },
            },
            'precisionMode': TICK_SIZE,
            'exceptions': {
                '104': OrderNotFound,
                '107': BadRequest,
                '108': BadSymbol,
                '405': OnMaintenance,
            },
            'commonCurrencies': {
                'SOC': 'Soda Coin',
            },
        });
    }
    /**
     * @method
     * @name coinone#fetchCurrencies
     * @description fetches all available currencies on an exchange
     * @see https://docs.coinone.co.kr/reference/currencies
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an associative dictionary of currencies
     */
    async fetchCurrencies(params = {}) {
        const response = await this.v2PublicGetCurrencies(params);
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "server_time": 1701054555578,
        //         "currencies": [
        //           {
        //             "name": "Polygon",
        //             "symbol": "MATIC",
        //             "deposit_status": "normal",
        //             "withdraw_status": "normal",
        //             "deposit_confirm_count": 150,
        //             "max_precision": 8,
        //             "deposit_fee": "0.0",
        //             "withdrawal_min_amount": "1.0",
        //             "withdrawal_fee": "3.0"
        //           }
        //         ]
        //     }
        //
        const result = {};
        const currencies = this.safeList(response, 'currencies', []);
        for (let i = 0; i < currencies.length; i++) {
            const entry = currencies[i];
            const id = this.safeString(entry, 'symbol');
            const name = this.safeString(entry, 'name');
            const code = this.safeCurrencyCode(id);
            const withdrawStatus = this.safeString(entry, 'withdraw_status', '');
            const depositStatus = this.safeString(entry, 'deposit_status', '');
            const isWithdrawEnabled = withdrawStatus === 'normal';
            const isDepositEnabled = depositStatus === 'normal';
            result[code] = {
                'id': id,
                'code': code,
                'info': entry,
                'name': name,
                'active': isWithdrawEnabled && isDepositEnabled,
                'deposit': isDepositEnabled,
                'withdraw': isWithdrawEnabled,
                'fee': this.safeNumber(entry, 'withdrawal_fee'),
                'precision': this.parseNumber(this.parsePrecision(this.safeString(entry, 'max_precision'))),
                'limits': {
                    'amount': {
                        'min': undefined,
                        'max': undefined,
                    },
                    'withdraw': {
                        'min': this.safeNumber(entry, 'withdrawal_min_amount'),
                        'max': undefined,
                    },
                },
                'networks': {},
            };
        }
        return result;
    }
    /**
     * @method
     * @name coinone#fetchMarkets
     * @description retrieves data on all markets for coinone
     * @see https://docs.coinone.co.kr/v1.0/reference/tickers
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} an array of objects representing market data
     */
    async fetchMarkets(params = {}) {
        const request = {
            'quote_currency': 'KRW',
        };
        const response = await this.v2PublicGetTickerNewQuoteCurrency(request);
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "server_time": 1701067923060,
        //         "tickers": [
        //             {
        //                 "quote_currency": "krw",
        //                 "target_currency": "stg",
        //                 "timestamp": 1701067920001,
        //                 "high": "667.5",
        //                 "low": "667.5",
        //                 "first": "667.5",
        //                 "last": "667.5",
        //                 "quote_volume": "0.0",
        //                 "target_volume": "0.0",
        //                 "best_asks": [
        //                     {
        //                         "price": "777.0",
        //                         "qty": "73.9098"
        //                     }
        //                 ],
        //                 "best_bids": [
        //                     {
        //                         "price": "690.8",
        //                         "qty": "40.7768"
        //                     }
        //                 ],
        //                 "id": "1701067920001001"
        //             }
        //         ]
        //     }
        //
        const tickers = this.safeList(response, 'tickers', []);
        const result = [];
        for (let i = 0; i < tickers.length; i++) {
            const entry = this.safeValue(tickers, i);
            const id = this.safeString(entry, 'id');
            const baseId = this.safeStringUpper(entry, 'target_currency');
            const quoteId = this.safeStringUpper(entry, 'quote_currency');
            const base = this.safeCurrencyCode(baseId);
            const quote = this.safeCurrencyCode(quoteId);
            result.push({
                'id': id,
                'symbol': base + '/' + quote,
                'base': base,
                'quote': quote,
                'settle': undefined,
                'baseId': baseId,
                'quoteId': quoteId,
                'settleId': undefined,
                'type': 'spot',
                'spot': true,
                'margin': false,
                'swap': false,
                'future': false,
                'option': false,
                'active': undefined,
                'contract': false,
                'linear': undefined,
                'inverse': undefined,
                'contractSize': undefined,
                'expiry': undefined,
                'expiryDatetime': undefined,
                'strike': undefined,
                'optionType': undefined,
                'precision': {
                    'amount': this.parseNumber('1e-8'),
                    'price': this.parseNumber('1e-4'),
                    'cost': this.parseNumber('1e-8'),
                },
                'limits': {
                    'leverage': {
                        'min': undefined,
                        'max': undefined,
                    },
                    'amount': {
                        'min': undefined,
                        'max': undefined,
                    },
                    'price': {
                        'min': undefined,
                        'max': undefined,
                    },
                    'cost': {
                        'min': undefined,
                        'max': undefined,
                    },
                },
                'created': undefined,
                'info': entry,
            });
        }
        return result;
    }
    parseBalance(response) {
        const result = { 'info': response };
        const balances = this.safeList(response, 'balances')
        for (let i = 0; i < balances.length; i++) {
            const balance = balances[i];
            const currencyId = this.safeString(balance, 'currency');
            const code = this.safeCurrencyCode(currencyId);
            const account = this.account();
            account['free'] = this.safeString(balance, 'available');
            account['used'] = this.safeString(balance, 'limit');
            result[code] = account;
        }
        return this.safeBalance(result);
    }
    /**
     * @method
     * @name coinone#fetchBalance
     * @description query for balance and get the amount of funds available for trading or funds locked in orders
     * @see https://docs.coinone.co.kr/v1.0/reference/v21
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
     */
    async fetchBalance(params = {}) {
        await this.loadMarkets();
        const response = await this.v2_1PrivatePostAccountBalanceAll(params);
        return this.parseBalance(response);
    }
    /**
     * @method
     * @name coinone#fetchOrderBook
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://docs.coinone.co.kr/v1.0/reference/orderbook
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
     */
    async fetchOrderBook(symbol, limit = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        if (limit !== undefined) {
            request['size'] = limit; // only support 5, 10, 15, 16
        }
        const response = await this.v2PublicGetOrderbookQuoteCurrencyTargetCurrency(this.extend(request, params));
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "timestamp": 1701071108673,
        //         "id": "1701071108673001",
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "order_book_unit": "0.0",
        //         "bids": [
        //             {
        //                 "price": "50048000",
        //                 "qty": "0.01080229"
        //             }
        //         ],
        //         "asks": [
        //             {
        //                 "price": "50058000",
        //                 "qty": "0.00272592"
        //             }
        //         ]
        //     }
        //
        const timestamp = this.safeInteger(response, 'timestamp');
        return this.parseOrderBook(response, market['symbol'], timestamp, 'bids', 'asks', 'price', 'qty');
    }
    /**
     * @method
     * @name coinone#fetchTickers
     * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
     * @see https://docs.coinone.co.kr/v1.0/reference/tickers
     * @see https://docs.coinone.co.kr/v1.0/reference/ticker
     * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async fetchTickers(symbols = undefined, params = {}) {
        await this.loadMarkets();
        symbols = this.marketSymbols(symbols);
        const request = {
            'quote_currency': 'KRW',
        };
        let market = undefined;
        let response = undefined;
        if (symbols !== undefined) {
            const first = this.safeString(symbols, 0);
            market = this.market(first);
            request['quote_currency'] = market['quote'];
            request['target_currency'] = market['base'];
            response = await this.v2PublicGetTickerNewQuoteCurrencyTargetCurrency(this.extend(request, params));
        }
        else {
            response = await this.v2PublicGetTickerNewQuoteCurrency(this.extend(request, params));
        }
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "server_time": 1701073358487,
        //         "tickers": [
        //             {
        //                 "quote_currency": "krw",
        //                 "target_currency": "btc",
        //                 "timestamp": 1701073357818,
        //                 "high": "50543000.0",
        //                 "low": "49945000.0",
        //                 "first": "50487000.0",
        //                 "last": "50062000.0",
        //                 "quote_volume": "11349804285.3859",
        //                 "target_volume": "226.07268994",
        //                 "best_asks": [
        //                     {
        //                         "price": "50081000.0",
        //                         "qty": "0.18471358"
        //                     }
        //                 ],
        //                 "best_bids": [
        //                     {
        //                         "price": "50062000.0",
        //                         "qty": "0.04213455"
        //                     }
        //                 ],
        //                 "id": "1701073357818001"
        //             }
        //         ]
        //     }
        //
        const data = this.safeList(response, 'tickers', []);
        return this.parseTickers(data, symbols);
    }
    /**
     * @method
     * @name coinone#fetchTicker
     * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.coinone.co.kr/v1.0/reference/ticker
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async fetchTicker(symbol, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        const response = await this.v2PublicGetTickerNewQuoteCurrencyTargetCurrency(this.extend(request, params));
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "server_time": 1701073358487,
        //         "tickers": [
        //             {
        //                 "quote_currency": "krw",
        //                 "target_currency": "btc",
        //                 "timestamp": 1701073357818,
        //                 "high": "50543000.0",
        //                 "low": "49945000.0",
        //                 "first": "50487000.0",
        //                 "last": "50062000.0",
        //                 "quote_volume": "11349804285.3859",
        //                 "target_volume": "226.07268994",
        //                 "best_asks": [
        //                     {
        //                         "price": "50081000.0",
        //                         "qty": "0.18471358"
        //                     }
        //                 ],
        //                 "best_bids": [
        //                     {
        //                         "price": "50062000.0",
        //                         "qty": "0.04213455"
        //                     }
        //                 ],
        //                 "id": "1701073357818001"
        //             }
        //         ]
        //     }
        //
        const data = this.safeList(response, 'tickers', []);
        const ticker = this.safeDict(data, 0, {});
        return this.parseTicker(ticker, market);
    }
    parseTicker(ticker, market = undefined) {
        //
        //     {
        //         "quote_currency": "krw",
        //         "target_currency": "btc",
        //         "timestamp": 1701073357818,
        //         "high": "50543000.0",
        //         "low": "49945000.0",
        //         "first": "50487000.0",
        //         "last": "50062000.0",
        //         "quote_volume": "11349804285.3859",
        //         "target_volume": "226.07268994",
        //         "best_asks": [
        //             {
        //                 "price": "50081000.0",
        //                 "qty": "0.18471358"
        //             }
        //         ],
        //         "best_bids": [
        //             {
        //                 "price": "50062000.0",
        //                 "qty": "0.04213455"
        //             }
        //         ],
        //         "id": "1701073357818001"
        //     }
        //
        const timestamp = this.safeInteger(ticker, 'timestamp');
        const last = this.safeString(ticker, 'last');
        const asks = this.safeList(ticker, 'best_asks', []);
        const bids = this.safeList(ticker, 'best_bids', []);
        const baseId = this.safeString(ticker, 'target_currency');
        const quoteId = this.safeString(ticker, 'quote_currency');
        const base = this.safeCurrencyCode(baseId);
        const quote = this.safeCurrencyCode(quoteId);
        return this.safeTicker({
            'symbol': base + '/' + quote,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'high': this.safeString(ticker, 'high'),
            'low': this.safeString(ticker, 'low'),
            'bid': this.safeString(bids, 'price'),
            'bidVolume': this.safeString(bids, 'qty'),
            'ask': this.safeString(asks, 'price'),
            'askVolume': this.safeString(asks, 'qty'),
            'vwap': undefined,
            'open': this.safeString(ticker, 'first'),
            'close': last,
            'last': last,
            'previousClose': undefined,
            'change': undefined,
            'percentage': undefined,
            'average': undefined,
            'baseVolume': this.safeString(ticker, 'target_volume'),
            'quoteVolume': this.safeString(ticker, 'quote_volume'),
            'info': ticker,
        }, market);
    }
    parseTrade(trade, market = undefined) {
        //
        // fetchTrades (public)
        //
        //     {
        //         "id": "1701075265708001",
        //         "timestamp": 1701075265708,
        //         "price": "50020000",
        //         "qty": "0.00155177",
        //         "is_seller_maker": false
        //     }
        //
        // fetchMyTrades (private)
        //
        //     {
        //         "trade_id": "0e2bb80f-1e4d-11e9-9ec7-00e04c3600d1",
        //         "order_id": "0e2b9627-1e4d-11e9-9ec7-00e04c3600d2",
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "order_type": "LIMIT",
        //         "is_ask": true,
        //         "is_maker": true,
        //         "price": "8420",
        //         "qty": "0.1599",
        //         "timestamp": 8964000,
        //         "fee_rate": "0.001",
        //         "fee": "162",
        //         "fee_currency": "KRW"
        //     }
        //
        const timestamp = this.safeInteger(trade, 'timestamp');
        market = this.safeMarket(undefined, market);
        const isSellerMaker = this.safeBool(trade, 'is_seller_maker');
        let side = undefined;
        if (isSellerMaker !== undefined) {
            side = isSellerMaker ? 'sell' : 'buy';
        }
        const priceString = this.safeString(trade, 'price');
        const amountString = this.safeString(trade, 'qty');
        const orderId = this.safeString(trade, 'orderId');
        let feeCostString = this.safeString(trade, 'fee');
        let fee = undefined;
        if (feeCostString !== undefined) {
            feeCostString = Precise.stringAbs(feeCostString);
            let feeRateString = this.safeString(trade, 'feeRate');
            feeRateString = Precise.stringAbs(feeRateString);
            const feeCurrencyCode = (side === 'sell') ? market['quote'] : market['base'];
            fee = {
                'cost': feeCostString,
                'currency': feeCurrencyCode,
                'rate': feeRateString,
            };
        }
        return this.safeTrade({
            'id': this.safeString(trade, 'id'),
            'info': trade,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'order': orderId,
            'symbol': market['symbol'],
            'type': undefined,
            'side': side,
            'takerOrMaker': undefined,
            'price': priceString,
            'amount': amountString,
            'cost': undefined,
            'fee': fee,
        }, market);
    }
    /**
     * @method
     * @name coinone#fetchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://docs.coinone.co.kr/v1.0/reference/recent-completed-orders
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
     */
    async fetchTrades(symbol, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        if (limit !== undefined) {
            request['size'] = Math.min(limit, 200);
        }
        const response = await this.v2PublicGetTradesQuoteCurrencyTargetCurrency(this.extend(request, params));
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "server_time": 1701075315771,
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "transactions": [
        //             {
        //                 "id": "1701075265708001",
        //                 "timestamp": 1701075265708,
        //                 "price": "50020000",
        //                 "qty": "0.00155177",
        //                 "is_seller_maker": false
        //             }
        //         ]
        //     }
        //
        const data = this.safeList(response, 'transactions', []);
        return this.parseTrades(data, market, since, limit);
    }
    /**
     * @method
     * @name coinone#createOrder
     * @description create a trade order
     * @see https://docs.coinone.co.kr/reference/place-order
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type must be 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async createOrder(symbol, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const postOnly = this.safeBool(params, 'postOnly', false);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
            'type': type.toUpperCase(),
            'side': side.toUpperCase(),
            'qty': amount,
            'price': price,
            'post_only': postOnly,
        };
        const response = await this.v2_1PrivatePostOrder(this.extend(request, params));
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "order_id": "8a82c561-40b4-4cb3-9bc0-9ac9ffc1d63b"
        //     }
        //
        return this.parseOrder(response, market);
    }
    /**
     * @method
     * @name coinone#fetchOrder
     * @description fetches information on an order made by the user
     * @param {string} id order id
     * @param {string} symbol unified symbol of the market the order was made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async fetchOrder(id, symbol = undefined, params = {}) {
        if (symbol === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchOrder() requires a symbol argument');
        }
        const clientOrderId = this.safeString2(params, 'clientOrderId', 'user_order_id');
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        if (clientOrderId === undefined) {
            request['order_id'] = id;
        }
        else {
            request['user_order_id'] = clientOrderId;
        }
        const response = await this.v2_1PrivatePostOrderDetail(this.extend(request, params));
        const order = this.safeDict(response, 'order', {});
        //
        // limit
        // {
        //     "result": "success",
        //     "error_code": "0",
        //     "order": {
        //         "order_id": "0f1c26d0-1e4d-11e9-9ec7-00e04c3600d7",
        //         "type": "LIMIT",
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "status": "CANCELED",
        //         "side": "BUY",
        //         "fee": "0",
        //         "fee_rate": "0.0",
        //         "average_executed_price": "0",
        //         "updated_at": 1680055490000,
        //         "ordered_at": 1680051059000,
        //         "price": "100000",
        //         "original_qty": "1",
        //         "executed_qty": "0",
        //         "canceled_qty": "1",
        //         "remain_qty": "0",
        //         "limit_price": null,
        //         "traded_amount": null,
        //         "original_amount": null,
        //         "canceled_amount": null,
        //         "is_triggered": null,
        //         "trigger_price": null
        //     }
        // }
        // market buy
        // {
        //     "result": "success",
        //     "error_code": "0",
        //     "order": {
        //         "order_id": "0f9d1473-1e4d-11e9-9ec7-00e04c3600d7",
        //         "type": "MARKET",
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "status": "CANCELED_UNDER_PRODUCT_UNIT",
        //         "side": "BUY",
        //         "fee": "1999.9999",
        //         "average_fee_rate": "0.002",
        //         "average_executed_price": "29959000",
        //         "updated_at": 1686133903000,
        //         "ordered_at": 1686133903000,
        //         "price": null,
        //         "original_qty": null,
        //         "executed_qty": "0.03337895",
        //         "canceled_qty": null,
        //         "remain_qty": null,
        //         "limit_price": "40000000",
        //         "traded_amount": "999999.963",
        //         "original_amount": "1000000",
        //         "canceled_amount": "0.0369",
        //         "is_triggered": null,
        //         "trigger_price": null
        //     }
        // }
        // market sell
        // {
        //     "result": "success",
        //     "error_code": "0",
        //     "order": {
        //         "order_id": "0f51301f-1e4d-11e9-9ec7-00e04c3600d7",
        //         "type": "MARKET",
        //         "quote_currency": "KRW",
        //         "target_currency": "BTC",
        //         "status": "FILLED",
        //         "side": "SELL",
        //         "fee": "73.36",
        //         "fee_rate": "0.002",
        //         "average_executed_price": "36680000",
        //         "updated_at": 1682385152000,
        //         "ordered_at": 1682385152000,
        //         "price": null,
        //         "original_qty": "0.001",
        //         "executed_qty": "0.001",
        //         "canceled_qty": "0",
        //         "remain_qty": null,
        //         "limit_price": "0.0001",
        //         "traded_amount": null,
        //         "original_amount": null,
        //         "canceled_amount": null,
        //         "is_triggered": null,
        //         "trigger_price": null
        //     }
        // }
        //
        return this.parseOrder(order, market);
    }
    parseOrderStatus(status) {
        const statuses = {
            'LIVE': 'open',
            'PARTIALLY_FILLED': 'open',
            'PARTIALLY_CANCELED': 'open',
            'FILLED': 'closed',
            'CANCELED': 'closed',
            'NOT_TRIGGERED': 'open',
            'NOT_TRIGGERED_PARTIALLY_CANCELED': 'open',
            'NOT_TRIGGERED_CANCELED': 'canceled',
            'CANCELED_NO_ORDER': 'canceled',
            'CANCELED_LIMIT_PRICE_EXCEED': 'canceled',
            'CANCELED_UNDER_PRODUCT_UNIT': 'canceled'
        };
        return this.safeString(statuses, status, status);
    }
    parseOrderType(type) {
        const types = {
            'MARKET': 'market',
            'LIMIT': 'limit',
            'STOP_LIMIT': 'limit'
        };
        return this.safeString(types, type, type);
    }
    parseOrder(order, market = undefined) {
        //
        // createOrder
        //
        //     {
        //         "result": "success",
        //         "error_code": "0",
        //         "order_id": "8a82c561-40b4-4cb3-9bc0-9ac9ffc1d63b"
        //     }
        //
        // fetchOrder
        //
        // {
        //     "order_id": "0f51301f-1e4d-11e9-9ec7-00e04c3600d7",
        //     "type": "MARKET",
        //     "quote_currency": "KRW",
        //     "target_currency": "BTC",
        //     "status": "FILLED",
        //     "side": "SELL",
        //     "fee": "73.36",
        //     "fee_rate": "0.002",
        //     "average_executed_price": "36680000",
        //     "updated_at": 1682385152000,
        //     "ordered_at": 1682385152000,
        //     "price": null,
        //     "original_qty": "0.001",
        //     "executed_qty": "0.001",
        //     "canceled_qty": "0",
        //     "remain_qty": null,
        //     "limit_price": "0.0001",
        //     "traded_amount": null,
        //     "original_amount": null,
        //     "canceled_amount": null,
        //     "is_triggered": null,
        //     "trigger_price": null
        // }
        //
        // fetchOpenOrders
        //
        // {
        //   "order_id": "0f460777-1e4d-11e9-9ec7-00e04c3600d7",
        //   "type": "LIMIT",
        //   "quote_currency": "KRW",
        //   "target_currency": "BTT",
        //   "price": "0.0009",
        //   "remain_qty": "10000000",
        //   "original_qty": "10000000",
        //   "canceled_qty": "0",
        //   "executed_qty": "0",
        //   "side": "BUY",
        //   "fee": "0",
        //   "fee_rate": "0.0",
        //   "average_executed_price": "0",
        //   "ordered_at": 1682058807000,
        //   "is_triggered": null,
        //   "trigger_price": null,
        //   "triggered_at": null
        // }
        //
        const id = this.safeString(order, 'order_id');
        let type = this.safeString(order, 'type');
        if (type !== undefined) {
            type = this.parseOrderType(type);
        }
        const baseId = this.safeString(order, 'target_currency');
        const quoteId = this.safeString(order, 'quote_currency');
        let base = undefined;
        let quote = undefined;
        if (baseId !== undefined) {
            base = this.safeCurrencyCode(baseId);
        }
        if (quoteId !== undefined) {
            quote = this.safeCurrencyCode(quoteId);
        }
        let symbol = undefined;
        if ((base !== undefined) && (quote !== undefined)) {
            symbol = base + '/' + quote;
            market = this.safeMarket(symbol, market, '/');
        }
        const timestamp = this.safeNumber(order, 'ordered_at');
        const lastUpdateTimestamp = this.safeNumber(order, 'updated_at');
        let datetime = undefined;
        if (timestamp !== undefined) {
            datetime = this.iso8601(timestamp);
        }
        let side = this.safeString(order, 'side');
        if (side !== undefined) {
            side = side.toLowerCase();
        }
        let status = this.safeString(order, 'status');
        if (status !== undefined) {
            status = this.parseOrderStatus(status);
        }
        let fee = undefined;
        const feeCostString = this.safeString(order, 'fee');
        if (feeCostString !== undefined) {
            fee = {
                'cost': feeCostString,
                'rate': this.safeString2(order, 'fee_rate', 'average_fee_rate'),
                'currency': quote,
            };
        }
        let remainQtyString = this.safeString(order, 'remain_qty');
        const canceledQtyString = this.safeString(order, "canceled_qty");
        if (remainQtyString === undefined) {
            remainQtyString = canceledQtyString;
        }
        else if (canceledQtyString !== undefined) {
            remainQtyString = Precise.stringAdd(remainQtyString, canceledQtyString);
        }

        return this.safeOrder({
            'info': order,
            'id': id,
            'clientOrderId': undefined,
            'timestamp': timestamp,
            'datetime': datetime,
            'lastUpdateTimestamp': lastUpdateTimestamp,
            'symbol': symbol,
            'type': type,
            'timeInForce': undefined,
            'postOnly': undefined,
            'side': side,
            'price': this.safeString(order, 'price'),
            'stopPrice': undefined,
            'triggerPrice': undefined,
            'cost': undefined,
            'average': this.safeString(order, 'average_executed_price'),
            'amount': this.safeString2(order, 'qty', 'original_qty'),
            'filled': this.safeString(order, 'executed_qty'),
            'remaining': remainQtyString,
            'status': status,
            'fee': fee,
            'trades': undefined,
        }, market);
    }
    /**
     * @method
     * @name coinone#fetchOpenOrders
     * @description fetch all unfilled currently open orders
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch open orders for
     * @param {int} [limit] the maximum number of  open orders structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async fetchOpenOrders(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        // The returned amount might not be same as the ordered amount. If an order is partially filled, the returned amount means the remaining amount.
        // For the same reason, the returned amount and remaining are always same, and the returned filled and cost are always zero.
        const request = {};
        if (symbol !== undefined) {
            await this.loadMarkets();
            const market = this.market(symbol);
            request['quote_currency'] = market['quote'];
            request['target_currency'] = market['base'];
        }
        const orderType = this.safeArray(params, 'types', 'order_type'); // ["LIMIT"], ["STOP_LIMIT"]
        if (orderType !== undefined) {
            request['order_type'] = orderType;
        }
        const response = await this.v2_1PrivatePostOrderActiveOrders(this.extend(request, params));
        //
        //     {
        //       "result": "success",
        //       "error_code": "0",
        //       "active_orders": [
        //         {
        //           "order_id": "0e30219d-1e4d-11e9-9ec7-00e04c3600d7",
        //           "type": "LIMIT",
        //           "quote_currency": "KRW",
        //           "target_currency": "BTC",
        //           "side": "SELL",
        //           "price": "75865000",
        //           "remain_qty": "0.0097",
        //           "original_qty": "0.01",
        //           "canceled_qty": "0",
        //           "executed_qty": "0.0003",
        //           "ordered_at": 1654238371000,
        //           "fee": "45.519",
        //           "fee_rate": "0.002",
        //           "average_executed_price": "75865000",
        //           "ordered_at": 1682382211000,
        //           "is_triggered": false,
        //           "trigger_price": "37000000",
        //           "triggered_at": null
        //         }
        //       ]
        //     }
        //
        const orders = this.safeList(response, 'active_orders', []);
        return this.parseOrders(orders, market, since, limit);
    }
    /**
     * @method
     * @name coinone#fetchClosedOrders
     * @description fetch all unfilled currently closed orders
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch closed orders for
     * @param {int} [limit] the maximum number of  closed orders structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async fetchClosedOrders(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        // The returned amount might not be same as the ordered amount. If an order is partially filled, the returned amount means the remaining amount.
        // For the same reason, the returned amount and remaining are always same, and the returned filled and cost are always zero.
        if (symbol === undefined) {
            throw new ExchangeError(this.id + ' fetchClosedOrders() allows fetching closed orders with a specific symbol');
        }
        if (since === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchClosedOrders() requires a since argument');
        }
        if (limit === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchClosedOrders() requires a limit argument');
        }
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'size': limit,
            'from_ts': since,
            'to_ts': this.now(),
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        const response = await this.v2_1PrivatePostOrderCompletedOrders(this.extend(request, params));
        //
        //     {
        //       "result": "success",
        //       "error_code": "0",
        //       "completed_orders": [
        //         {
        //           "order_id": "0e30219d-1e4d-11e9-9ec7-00e04c3600d7",
        //           "type": "LIMIT",
        //           "quote_currency": "KRW",
        //           "target_currency": "BTC",
        //           "side": "SELL",
        //           "price": "75865000",
        //           "remain_qty": "0.0097",
        //           "original_qty": "0.01",
        //           "canceled_qty": "0",
        //           "executed_qty": "0.0003",
        //           "ordered_at": 1654238371000,
        //           "fee": "45.519",
        //           "fee_rate": "0.002",
        //           "average_executed_price": "75865000"
        //         }
        //       ]
        //     }
        //
        const orders = this.safeList(response, 'completed_orders', []);
        return this.parseOrders(orders, market, since, limit);
    }
    /**
     * @method
     * @name coinone#fetchMyTrades
     * @description fetch all trades made by the user
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trades structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
     */
    async fetchMyTrades(symbol = undefined, since = undefined, limit = undefined, params = {}) {
        if (symbol === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchMyTrades() requires a symbol argument');
        }
        if (since === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchMyTrades() requires a since argument');
        }
        if (limit === undefined) {
            throw new ArgumentsRequired(this.id + ' fetchMyTrades() requires a limit argument');
        }
        await this.loadMarkets();
        const market = this.market(symbol);
        const toTradeId = this.safeString2(params, 'orderId', 'to_trade_id');
        const request = {
            'size': limit,
            'from_ts': since,
            'to_ts': this.now(),
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        if (toTradeId !== undefined) {
            request['to_trade_id'] = toTradeId;
        }
        const response = await this.v2_1PrivatePostOrderCompletedOrders(this.extend(request, params));
        //
        // despite the name of the endpoint it returns trades which may have a duplicate orderId
        // https://github.com/ccxt/ccxt/pull/7067
        //
        //     {
        //          "result": "success",
        //          "error_code": "0",
        //          "completed_orders": [
        //              {
        //              "trade_id": "0e2bb80f-1e4d-11e9-9ec7-00e04c3600d1",
        //              "order_id": "0e2b9627-1e4d-11e9-9ec7-00e04c3600d2",
        //              "quote_currency": "KRW",
        //              "target_currency": "BTC",
        //              "order_type": "LIMIT",
        //              "is_ask": true,
        //              "is_maker": true,
        //              "price": "8420",
        //              "qty": "0.1599",
        //              "timestamp": 8964000,
        //              "fee_rate": "0.001",
        //              "fee": "162",
        //              "fee_currency": "KRW"
        //              },
        //          ]
        //     }
        //
        const completeOrders = this.safeList(response, 'complete_orders', []);
        return this.parseTrades(completeOrders, market, since, limit);
    }
    /**
     * @method
     * @name coinone#cancelOrder
     * @description cancels an open order
     * @param {string} id order id
     * @param {string} symbol unified symbol of the market the order was made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async cancelOrder(id, symbol = undefined, params = {}) {
        if (symbol === undefined) {
            // eslint-disable-next-line quotes
            throw new ArgumentsRequired(this.id + " cancelOrder() requires a symbol argument. To cancel the order, pass a symbol argument and {'price': 12345, 'qty': 1.2345, 'is_ask': 0} in the params argument of cancelOrder.");
        }
        const clientOrderId = this.safeString2(params, 'clientOrderId', 'user_order_id');
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'quote_currency': market['quote'],
            'target_currency': market['base'],
        };
        if (clientOrderId === undefined) {
            request['order_id'] = id;
        }
        else {
            request['user_order_id'] = clientOrderId;
        }
        const response = await this.v2_1PrivatePostOrderCancel(this.extend(request, params));
        //
        // {
        //   "result": "success",
        //   "error_code": "0",
        //   "order_id": "d85cc6af-b131-4398-b269-ddbafa760a39",
        //   "price": "26231000.0",
        //   "qty": "0.002",
        //   "remain_qty": "0.0",
        //   "side": "BUY",
        //   "original_qty": "0.005",
        //   "traded_qty": "0.003",
        //   "canceled_qty": "0.002",
        //   "fee": "26231.0",
        //   "fee_rate": "0.001",
        //   "avg_price": "26231000.0",
        //   "canceled_at": 1650525935,
        //   "ordered_at": 1650125935
        // }
        //
        return this.parseOrder(response, market);
    }
    /**
     * @method
     * @name coinone#fetchDepositAddresses
     * @description fetch deposit addresses for multiple currencies and chain types
     * @param {string[]|undefined} codes list of unified currency codes, default is undefined
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a list of [address structures]{@link https://docs.ccxt.com/#/?id=address-structure}
     */
    async fetchDepositAddresses(codes = undefined, params = {}) {
        await this.loadMarkets();
        const response = await this.v2PrivatePostAccountDepositAddress(params);
        //
        //     {
        //         "result": "success",
        //         "errorCode": "0",
        //         "walletAddress": {
        //             "matic": null,
        //             "btc": "mnobqu4i6qMCJWDpf5UimRmr8JCvZ8FLcN",
        //             "xrp": null,
        //             "xrp_tag": "-1",
        //             "kava": null,
        //             "kava_memo": null,
        //         }
        //     }
        //
        const walletAddress = this.safeDict(response, 'walletAddress', {});
        const keys = Object.keys(walletAddress);
        const result = {};
        for (let i = 0; i < keys.length; i++) {
            const key = keys[i];
            const value = walletAddress[key];
            if ((!value) || (value === '-1')) {
                continue;
            }
            const parts = key.split('_');
            const currencyId = this.safeValue(parts, 0);
            const secondPart = this.safeValue(parts, 1);
            const code = this.safeCurrencyCode(currencyId);
            let depositAddress = this.safeValue(result, code);
            if (depositAddress === undefined) {
                depositAddress = {
                    'info': value,
                    'currency': code,
                    'network': undefined,
                    'address': undefined,
                    'tag': undefined,
                };
            }
            const address = this.safeString(depositAddress, 'address', value);
            this.checkAddress(address);
            depositAddress['address'] = address;
            depositAddress['info'] = address;
            if ((secondPart === 'tag' || secondPart === 'memo')) {
                depositAddress['tag'] = value;
                depositAddress['info'] = [address, value];
            }
            result[code] = depositAddress;
        }
        return result;
    }
    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        const request = this.implodeParams(path, params);
        const query = this.omit(params, this.extractParams(path));
        let url = this.urls['api']['rest'] + '/';
        let nonce;
        if (api === 'v2Public') {
            url = this.urls['api']['v2Public'] + '/';
            api = 'public';
        }
        else if (api === 'v2Private') {
            url = this.urls['api']['v2Private'] + '/';
            nonce = this.nonce().toString();
        }
        else if (api === 'v2_1Private') {
            url = this.urls['api']['v2_1Private'] + '/';
            nonce = this.uuid();
        }
        if (api === 'public') {
            url += request;
            if (Object.keys(query).length) {
                url += '?' + this.urlencode(query);
            }
        }
        else {
            this.checkRequiredCredentials();
            url += request;
            const json = this.json(this.extend({
                'access_token': this.apiKey,
                'nonce': nonce,
            }, params));
            const payload = this.stringToBase64(json);
            body = payload;
            const secret = this.secret.toUpperCase();
            const signature = this.hmac(this.encode(payload), this.encode(secret), sha512);
            headers = {
                'Content-Type': 'application/json',
                'X-COINONE-PAYLOAD': payload,
                'X-COINONE-SIGNATURE': signature,
            };
        }
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
    handleErrors(code, reason, url, method, headers, body, response, requestHeaders, requestBody) {
        if (response === undefined) {
            return undefined; // fallback to default error handler
        }
        //
        //     {"result":"error","error_code":"107","error_msg":"Parameter value is wrong"}
        //     {"result":"error","error_code":"108","error_msg":"Unknown CryptoCurrency"}
        //
        const errorCode = this.safeString(response, 'error_code');
        if (errorCode !== undefined && errorCode !== '0') {
            const feedback = this.id + ' ' + body;
            this.throwExactlyMatchedException(this.exceptions, errorCode, feedback);
            throw new ExchangeError(feedback); // unknown message
        }
        return undefined;
    }
}
